/*
 * LCD_Private.h
 *
 *  Created on: Jul 30, 2024
 *      Author: Abdalrahman
 */

#ifndef INCLUDE_HAL_LCD_LCD_PRIVATE_H_
#define INCLUDE_HAL_LCD_LCD_PRIVATE_H_

#define DONTCARE 0

#define FUCNTION_SET 			CONC_BIT(0,0,1,LCD_DATA_LENGHT,LCD_NO_OF_LINES,LCD_CHAR_SIZE,DONTCARE,DONTCARE)
#define DISPLAY_ON_OFF_CONTROL  CONC_BIT(0,0,0,0,1,LCD_DISPLAY_STATUS,LCD_CURSOR_DISPLAY,LCD_CURSOR_BLINK)
#define DISPLAY_CLEAR 			0x01
#define ENTRY_MODE_SET 			CONC_BIT(0,0,0,0,0,1,LCD_DISPLAY_DIRECTION,SHIFT_ENABLE)

#define ROW1_BASE_ADD 127
#define ROW2_BASE_ADD 191






#endif /* INCLUDE_HAL_LCD_LCD_PRIVATE_H_ */
